"""initial slice1 schema

Revision ID: d0a476450f0c
Revises: 
Create Date: 2026-05-17 21:57:55.650075

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a476450f0c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_assertion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('HOST', 'CLUSTER', 'SITE', 'GLOBAL', name='assertionscope'), nullable=False),
    sa.Column('scope_target', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('SSH_COMMAND', 'HTTP_CHECK', 'API_QUERY', 'OBSERVATION_PREDICATE', 'FILE_HASH', name='assertionkind'), nullable=False),
    sa.Column('verifier_spec', sa.JSON(), nullable=False),
    sa.Column('severity_on_fail', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='findingseverity'), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=True),
    sa.Column('artifact_link', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('host',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('netbox_device_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('primary_ip', sa.String(length=45), nullable=True),
    sa.Column('arch', sa.Enum('AMD64', 'ARM64', 'ARM', 'OTHER', name='architecture'), nullable=False),
    sa.Column('power_policy', sa.Enum('ALWAYS_ON', 'WOL_ON_DEMAND', 'MANUAL', name='powerpolicy'), nullable=False),
    sa.Column('expected_power_state', sa.Enum('ON', 'OFF', 'EITHER', 'UNKNOWN', name='powerstate'), nullable=False),
    sa.Column('discovery_source', sa.Enum('MANUAL', 'UNIFI', 'PROXMOX', 'K8S', 'KERNEL_PROBE', 'CLOUDFLARE', 'NETBOX', name='discoverysource'), nullable=False),
    sa.Column('discovery_last_run', sa.DateTime(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_host_discovery_last_run'), ['discovery_last_run'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_hostname'), ['hostname'], unique=False)
        batch_op.create_index('ix_host_hostname_lower', ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_netbox_device_id'), ['netbox_device_id'], unique=True)

    op.create_table('operational_intent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('HOST', 'VM', 'LXC', 'SERVICE', 'CIRCUIT', name='intenttargettype'), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.Enum('RUNNING', 'STOPPED_BY_DESIGN', 'DECOMMISSIONING', 'REALIZED', 'STRAY', 'UNKNOWN', name='intentstate'), nullable=False),
    sa.Column('declared_at', sa.DateTime(), nullable=False),
    sa.Column('declared_by', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('review_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_intent_per_target')
    )
    with op.batch_alter_table('operational_intent', schema=None) as batch_op:
        batch_op.create_index('ix_intent_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_intent_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_intent_target_type'), ['target_type'], unique=False)

    op.create_table('physical_part',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('DIMM', 'SSD', 'HDD', 'NVME', 'NIC', 'PSU', 'GPU', 'CPU', 'OTHER', name='partkind'), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('wwid', sa.String(length=255), nullable=True),
    sa.Column('capacity_bytes', sa.BigInteger(), nullable=True),
    sa.Column('speed_mts', sa.Integer(), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physical_part', schema=None) as batch_op:
        batch_op.create_index('ix_part_kind_serial', ['kind', 'serial'], unique=False)
        batch_op.create_index('ix_part_kind_wwid', ['kind', 'wwid'], unique=False)
        batch_op.create_index(batch_op.f('ix_physical_part_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_physical_part_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_physical_part_wwid'), ['wwid'], unique=False)

    op.create_table('probe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('module_path', sa.String(length=512), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('required_privilege', sa.Enum('NONE', 'USER', 'SUDO', 'ROOT', 'API', name='privilegelevel'), nullable=False),
    sa.Column('produces_keys', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('probe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_probe_name'), ['name'], unique=True)

    op.create_table('reconciliation_finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('CONFIG_DRIFT', 'CONFIG_DRIFT_UNKNOWN', 'OUTAGE_STALE', 'STRAY_CONFIG', 'CHOKEPOINT', 'INVENTORY_GAP', 'CEPH_BOTTLENECK', 'LEGACY_WORKLOAD', 'UNKNOWN_WORKLOAD', 'STORAGE_PROVENANCE_DELTA', 'DISCOVERY_AGENTLESS_NEEDED', 'DRIFT_CANDIDATE', 'PROVENANCE_PARTIAL', 'INTRA_SITE_LINK_MANUAL', 'OTHER', name='findingkind'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='findingseverity'), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('affected', sa.JSON(), nullable=False),
    sa.Column('proposed_actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', name='findingstatus'), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('suppressed_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_finding', schema=None) as batch_op:
        batch_op.create_index('ix_finding_open', ['status', 'severity', 'last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_finding_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_reconciliation_finding_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_finding_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_finding_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_finding_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_finding_status'), ['status'], unique=False)

    op.create_table('assertion_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assertion_id', sa.Uuid(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'ERROR', 'SKIP', name='assertionstatus'), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assertion_id'], ['configuration_assertion.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['reconciliation_finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assertion_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assertion_run_assertion_id'), ['assertion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertion_run_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index('ix_assertion_run_latest', ['assertion_id', 'ran_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertion_run_ran_at'), ['ran_at'], unique=False)

    op.create_table('discovery_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=True),
    sa.Column('target_spec', sa.String(length=255), nullable=True),
    sa.Column('probe_id', sa.Uuid(), nullable=False),
    sa.Column('probe_name', sa.String(length=255), nullable=False),
    sa.Column('probe_version', sa.String(length=32), nullable=False),
    sa.Column('privilege_level', sa.Enum('NONE', 'USER', 'SUDO', 'ROOT', 'API', name='privilegelevel'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_run_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_run_probe_id'), ['probe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_run_probe_name'), ['probe_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_run_started_at'), ['started_at'], unique=False)

    op.create_table('proposal_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(), nullable=False),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('assertion_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artifact', sa.JSON(), nullable=False),
    sa.Column('affected', sa.JSON(), nullable=False),
    sa.Column('blast_radius', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'USER_ACCEPTED', 'USER_REJECTED', 'USER_DEFERRED', 'SUPERSEDED', 'EXPIRED', name='proposaloutcome'), nullable=False),
    sa.Column('outcome_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_by', sa.String(length=255), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assertion_id'], ['configuration_assertion.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['reconciliation_finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_log_assertion_id'), ['assertion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_log_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_log_proposed_at'), ['proposed_at'], unique=False)
        batch_op.create_index('ix_proposal_pending', ['outcome', 'proposed_at'], unique=False)

    op.create_table('observation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Enum('VERIFIED', 'INFERRED', 'ASSERTED', 'STALE', name='confidence'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('target_type', sa.Enum('HOST', 'VM', 'LXC', 'SERVICE', 'CIRCUIT', name='intenttargettype'), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['discovery_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.create_index('ix_obs_key_time', ['key', 'recorded_at'], unique=False)
        batch_op.create_index('ix_obs_target_key_time', ['target_type', 'target_id', 'key', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_target_type'), ['target_type'], unique=False)

    op.create_table('placement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.String(length=128), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Enum('VERIFIED', 'INFERRED', 'ASSERTED', 'STALE', name='confidence'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'UNIFI', 'PROXMOX', 'K8S', 'KERNEL_PROBE', 'CLOUDFLARE', 'NETBOX', name='discoverysource'), nullable=False),
    sa.Column('discovery_run_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_run.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['physical_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placement', schema=None) as batch_op:
        batch_op.create_index('ix_placement_current', ['part_id', 'to_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_placement_discovery_run_id'), ['discovery_run_id'], unique=False)
        batch_op.create_index('ix_placement_host_current', ['host_id', 'to_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_placement_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placement_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placement_to_date'), ['to_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_to_date'))
        batch_op.drop_index(batch_op.f('ix_placement_part_id'))
        batch_op.drop_index(batch_op.f('ix_placement_host_id'))
        batch_op.drop_index('ix_placement_host_current')
        batch_op.drop_index(batch_op.f('ix_placement_discovery_run_id'))
        batch_op.drop_index('ix_placement_current')

    op.drop_table('placement')
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_target_type'))
        batch_op.drop_index(batch_op.f('ix_observation_target_id'))
        batch_op.drop_index(batch_op.f('ix_observation_run_id'))
        batch_op.drop_index(batch_op.f('ix_observation_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_observation_key'))
        batch_op.drop_index('ix_obs_target_key_time')
        batch_op.drop_index('ix_obs_key_time')

    op.drop_table('observation')
    with op.batch_alter_table('proposal_log', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_pending')
        batch_op.drop_index(batch_op.f('ix_proposal_log_proposed_at'))
        batch_op.drop_index(batch_op.f('ix_proposal_log_finding_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_log_assertion_id'))

    op.drop_table('proposal_log')
    with op.batch_alter_table('discovery_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_run_started_at'))
        batch_op.drop_index(batch_op.f('ix_discovery_run_probe_name'))
        batch_op.drop_index(batch_op.f('ix_discovery_run_probe_id'))
        batch_op.drop_index(batch_op.f('ix_discovery_run_host_id'))

    op.drop_table('discovery_run')
    with op.batch_alter_table('assertion_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assertion_run_ran_at'))
        batch_op.drop_index('ix_assertion_run_latest')
        batch_op.drop_index(batch_op.f('ix_assertion_run_finding_id'))
        batch_op.drop_index(batch_op.f('ix_assertion_run_assertion_id'))

    op.drop_table('assertion_run')
    with op.batch_alter_table('reconciliation_finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_finding_status'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_finding_severity'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_finding_last_seen'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_finding_kind'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_finding_first_seen'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_finding_fingerprint'))
        batch_op.drop_index('ix_finding_open')

    op.drop_table('reconciliation_finding')
    with op.batch_alter_table('probe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_probe_name'))

    op.drop_table('probe')
    with op.batch_alter_table('physical_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physical_part_wwid'))
        batch_op.drop_index(batch_op.f('ix_physical_part_serial'))
        batch_op.drop_index(batch_op.f('ix_physical_part_kind'))
        batch_op.drop_index('ix_part_kind_wwid')
        batch_op.drop_index('ix_part_kind_serial')

    op.drop_table('physical_part')
    with op.batch_alter_table('operational_intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_intent_target_type'))
        batch_op.drop_index(batch_op.f('ix_operational_intent_target_id'))
        batch_op.drop_index('ix_intent_target')

    op.drop_table('operational_intent')
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_host_netbox_device_id'))
        batch_op.drop_index('ix_host_hostname_lower')
        batch_op.drop_index(batch_op.f('ix_host_hostname'))
        batch_op.drop_index(batch_op.f('ix_host_discovery_last_run'))

    op.drop_table('host')
    op.drop_table('configuration_assertion')
    # ### end Alembic commands ###
